language: python
python:
  # - "2.6"
  # - "2.7" #fails
  # - "3.3"
  # - "3.4" #fails
  - "3.5"
  - "3.6"
  # - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
  - "nightly"
# command to install dependencies
# before_install:
#   - sudo -H pip install --upgrade
env:
  - WITH_OPENCL=1
  - WITH_OPENCL=0

matrix:
  fast_finish: true
  config:
    WITH_OPENCL=1:
      addons:
        apt:
          packages:
          - python-pyopencl
          - python3-pyopencl
          - opencl-headers

  allow_failures:
      - python: '3.5'
        env:  WITH_OPENCL=1
      - python: '3.6'
        env:  WITH_OPENCL=1
      - python: '3.7-dev'
        env:  WITH_OPENCL=0
      - python: '3.7-dev'
        env:  WITH_OPENCL=1
      - python: 'nightly'
        env:  WITH_OPENCL=0
      - python: 'nightly'
        env:  WITH_OPENCL=1



install:
  - pip install --upgrade pip
  - pip install --ignore-installed setuptools
  - pip install --ignore-installed wheel
  - pip install --ignore-installed pytest-cov
  - pip install --ignore-installed pytest
  - if [[ "$WITH_OPENCL" == "1" ]]; then pip install --ignore-installed pyopencl; fi
  - python setup.py sdist
  - pip install -e .
  - export DISPLAY=:0.0
  # - python -c "import pyconrad.autoinit;pyconrad.edu().stanford.rsl.conrad.utils.Configuration.initConfig()"
# command to run tests
script:
  - python -c "import pyconrad"
  - pytest # or py.test for Python versions 3.5 and below
os:
  - linux
  # - osx

addons:
  apt:
    packages:
    - python-pyopencl
    - python3-pyopencl
    - opencl-headers

notifications:
  email: true
